---
title: "Synthetic Controls"
date: 'Report generated `r format(Sys.time(), "%A, %B %d, %Y")`'
output:
 html_document:
  toc: TRUE
  toc_float: TRUE
params:
 update_packages: TRUE
 install_packages: TRUE
 country: ''
 n_seasons: ''
 exclude_covar: ''
 exclude_group: ''
 code_change: FALSE
 input_directory: ''
 output_directory: ''
 file_name: ''
 group_name: ''
 date_name: ''
 outcome_name: ''
 denom_name: ''
 start_date: ''
 intervention_date: ''
 end_date: ''
 pre_period: ''
 post_period: ''
 eval_period: ''
---

```{r setup, include = FALSE}
library('knitr', quietly = TRUE)
opts_chunk$set(echo = FALSE)
```

```{r params, include = FALSE, eval = FALSE}
update_packages <- params$update_packages
install_packages <- params$install_packages

country       <- params$country
n_seasons     <- params$n_seasons
exclude_covar <- params$exclude_covar
exclude_group <- params$exclude_group
code_change   <- params$code_change

input_directory  <- params$input_directory
output_directory <- params$output_directory
file_name        <- params$file_name

group_name   <- params$group_name
date_name    <- params$date_name
outcome_name <- params$outcome_name
denom_name   <- params$denom_name

start_date        <- params$start_date
intervention_date <- params$intervention_date
end_date          <- params$end_date
pre_period        <- params$pre_period
post_period       <- params$post_period
eval_period       <- params$eval_period
```

```{r analysis, include = FALSE}
source('synthetic_control_analysis.R', local = TRUE)
```

#`r country` Results

```{r sparse}
if (!is.null(names(sparse_groups[sparse_groups])) && length(names(sparse_groups[sparse_groups])) != 0) {
	kable(data.frame('Sparse Groups' = names(sparse_groups[sparse_groups]), check.names = FALSE), align = 'c')
}
```

##combine estimates
```{r Comparison of estimates from different models}
kable( cbind.data.frame(rr_mean_full_intervals,rr_mean_time_intervals,rr_mean_time_no_offset_intervals, rr_mean_pca_intervals), align = 'c')
```

#Plot of Rate ratios, with size proportional to cross validation weights
```{r fig.width=5, fig.height=3, fig.align = "center", dpi=300, echo=FALSE}
#Compare rate ratios, with size of marker scaled to cross val weights
		ggplot(rr_mean_combo, aes(x=group.index, y=mean.rr, color=Model,group=Model)) + 
	  geom_errorbar(aes(ymin=lcl, ymax=ucl), colour="gray", width=.0) +
	  geom_point(aes(shape=Model, size=est.index))+
     scale_shape_manual(values=c(15, 16, 17,18))+
	  scale_size_manual(values=c(point.weights2$value*2)) + #Scales area, which is optimal for bubbl plot
	  #geom_errorbar(rr_mean_combo,aes(ymin=lcl, ymax=ucl), colour="black", width=.1) +
	  theme_bw() +
	  guides(size=FALSE)+ #turn off size axis
	  scale_colour_manual(values=cbPalette)+
	  labs(x = "Group", y="Rate ratio")+
	  geom_hline(yintercept = 1, colour='gray',linetype = 2)+
	  theme(axis.line = element_line(colour = "black"),
	        legend.position=c(0.2, 0.9),
	        panel.grid.major = element_blank(),
	        panel.grid.minor = element_blank(),
	        panel.border = element_blank(),
	        panel.background = element_blank()) 
```

##Weights for each of the models from cross validation
```{r Comparison of Cross validation Weights from different models}
if(crossval){
kable(stacking_weights.all, align = 'c')
} else{
      print("Cross-validation not performed")
    }
```
  
##Inclusion Probabilities
```{r incl, include = FALSE}
incl_probs <- NULL
	for (group in groups) {
	    incl_prob=impact_full[[group]]$inclusion_probs[-c(1:(n_seasons-1)),]
	    incl_prob<- incl_prob[order(-incl_prob$inclusion_probs),]
	    incl_prob<-incl_prob[c(1:3),]
	    incl_prob2<-incl_prob[,2]
	    incl_prob_names=incl_prob[,1]
			incl_prob3 <- data.frame('Group' = group, 'Greatest Inclusion Variable' = incl_prob_names[1], 'Greatest Inclusion Probability' = incl_prob2[1], 'Second Greatest Inclusion Variable' = incl_prob_names[2], 'Second Greatest Inclusion Probability' = incl_prob2[2], 'Third Greatest Inclusion Variable' = incl_prob_names[3], 'Third Greatest Inclusion Probability' = incl_prob2[3], check.names = FALSE)
			incl_probs <- rbind(incl_probs, incl_prob3)
		}
rownames(incl_probs) <- NULL
```

```{r incl_table}
kable(incl_probs, align = 'c')
```

##Weight Sensitivity Analysis
```{r sensitivity}
kable(sensitivity_table_intervals, align = 'c')
```


##Plots
```{r plots,fig.height =3 , fig.width = 5, fig.align = "center", dpi=300,results = 'asis'}
source('synthetic_control_plot.R', local = TRUE)
```